In [1]:
import numpy as np

In [3]:
x = np.array([40,67,57,90])
print(x)
print(type(x))
print(x.dtype)

[40 67 57 90]
<class 'numpy.ndarray'>
int32


In [5]:
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [9]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [33]:
c = np.arrange(3,20)
print(c)
type(c)

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
# Use astype() to convert the data type
a1 = np.array([[3,4,5,6],[7,2,8,5]])
print(a1)
a1.dtype

[[3 4 5 6]
 [7 2 8 5]]


dtype('int32')

In [23]:
c = np.arrange(3,20)
print(c)
type(c)

AttributeError: module 'numpy' has no attribute 'arrange'

In [19]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [21]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[13 26 22]
[14 19 28]


In [27]:
print(a2)
print(np.mean(a2, axis = 1))
print(np.mean(a2, axis = 0))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [31]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [43]:
a4 = np.array([3,4,5],[7,9,4],[9,1,6],[10,9,18])
print([1:3],[0:2])

SyntaxError: invalid syntax (2989985494.py, line 2)